version: '3.2'
services:
  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  web:
    build:
      context: .
      dockerfile: docker/httpd/Dockerfile
      args:
        APACHE_LOG_DIR: /var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    environment:
      APACHE_LOG_DIR: /var/log/apache2
    volumes:
      - .:/var/www/html
      - ./docker/httpd/custom.conf:/usr/local/apache2/conf/custom.conf
      - ./docker/httpd/vhost.conf:/usr/local/apache2/conf/vhost.conf
